/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedApiEndpointsRouteImport } from './routes/_authenticated.api-endpoints'
import { Route as AuthenticatedAssetsRouteImport } from './routes/_authenticated.assets'
import { Route as AuthenticatedAuditLogsRouteImport } from './routes/_authenticated.audit-logs'
import { Route as AuthenticatedChangesRouteImport } from './routes/_authenticated.changes'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated.jobs'
import { Route as AuthenticatedJsFilesRouteImport } from './routes/_authenticated.js-files'
import { Route as AuthenticatedLiveHostsRouteImport } from './routes/_authenticated.live-hosts'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated.notes'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated.notifications'
import { Route as AuthenticatedProgramsRouteImport } from './routes/_authenticated.programs'
import { Route as AuthenticatedReviewRouteImport } from './routes/_authenticated.review'
import { Route as AuthenticatedRulesRouteImport } from './routes/_authenticated.rules'
import { Route as AuthenticatedScopeRouteImport } from './routes/_authenticated.scope'
import { Route as AuthenticatedScoringRouteImport } from './routes/_authenticated.scoring'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated.tools'
import { Route as AuthenticatedUrlsRouteImport } from './routes/_authenticated.urls'
import { Route as AuthenticatedAssetsIndexRouteImport } from './routes/_authenticated.assets.index'
import { Route as AuthenticatedAssetsAssetIdRouteImport } from './routes/_authenticated.assets.$assetId'
import { Route as AuthenticatedEndpointsEndpointIdRouteImport } from './routes/_authenticated.endpoints.$endpointId'
import { Route as AuthenticatedProgramsProgramIdRouteImport } from './routes/_authenticated.programs.$programId'
import { Route as AuthenticatedReviewAssetIdRouteImport } from './routes/_authenticated.review.$assetId'
import { Route as AuthenticatedScannerFindingsFindingIdRouteImport } from './routes/_authenticated.scanner-findings.$findingId'
import { Route as AuthenticatedUrlsIndexRouteImport } from './routes/_authenticated.urls.index'
import { Route as AuthenticatedUrlsUrlIdRouteImport } from './routes/_authenticated.urls.$urlId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApiEndpointsRoute =
  AuthenticatedApiEndpointsRouteImport.update({
    id: '/api-endpoints',
    path: '/api-endpoints',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssetsRoute = AuthenticatedAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditLogsRoute = AuthenticatedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChangesRoute = AuthenticatedChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJsFilesRoute = AuthenticatedJsFilesRouteImport.update({
  id: '/js-files',
  path: '/js-files',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLiveHostsRoute = AuthenticatedLiveHostsRouteImport.update({
  id: '/live-hosts',
  path: '/live-hosts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProgramsRoute = AuthenticatedProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReviewRoute = AuthenticatedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRulesRoute = AuthenticatedRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScopeRoute = AuthenticatedScopeRouteImport.update({
  id: '/scope',
  path: '/scope',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScoringRoute = AuthenticatedScoringRouteImport.update({
  id: '/scoring',
  path: '/scoring',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUrlsRoute = AuthenticatedUrlsRouteImport.update({
  id: '/urls',
  path: '/urls',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssetsIndexRoute =
  AuthenticatedAssetsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAssetsRoute,
  } as any)
const AuthenticatedAssetsAssetIdRoute =
  AuthenticatedAssetsAssetIdRouteImport.update({
    id: '/$assetId',
    path: '/$assetId',
    getParentRoute: () => AuthenticatedAssetsRoute,
  } as any)
const AuthenticatedEndpointsEndpointIdRoute =
  AuthenticatedEndpointsEndpointIdRouteImport.update({
    id: '/endpoints/$endpointId',
    path: '/endpoints/$endpointId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProgramsProgramIdRoute =
  AuthenticatedProgramsProgramIdRouteImport.update({
    id: '/$programId',
    path: '/$programId',
    getParentRoute: () => AuthenticatedProgramsRoute,
  } as any)
const AuthenticatedReviewAssetIdRoute =
  AuthenticatedReviewAssetIdRouteImport.update({
    id: '/$assetId',
    path: '/$assetId',
    getParentRoute: () => AuthenticatedReviewRoute,
  } as any)
const AuthenticatedScannerFindingsFindingIdRoute =
  AuthenticatedScannerFindingsFindingIdRouteImport.update({
    id: '/scanner-findings/$findingId',
    path: '/scanner-findings/$findingId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUrlsIndexRoute = AuthenticatedUrlsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedUrlsRoute,
} as any)
const AuthenticatedUrlsUrlIdRoute = AuthenticatedUrlsUrlIdRouteImport.update({
  id: '/$urlId',
  path: '/$urlId',
  getParentRoute: () => AuthenticatedUrlsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/api-endpoints': typeof AuthenticatedApiEndpointsRoute
  '/assets': typeof AuthenticatedAssetsRouteWithChildren
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/changes': typeof AuthenticatedChangesRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/js-files': typeof AuthenticatedJsFilesRoute
  '/live-hosts': typeof AuthenticatedLiveHostsRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/programs': typeof AuthenticatedProgramsRouteWithChildren
  '/review': typeof AuthenticatedReviewRouteWithChildren
  '/rules': typeof AuthenticatedRulesRoute
  '/scope': typeof AuthenticatedScopeRoute
  '/scoring': typeof AuthenticatedScoringRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/urls': typeof AuthenticatedUrlsRouteWithChildren
  '/assets/$assetId': typeof AuthenticatedAssetsAssetIdRoute
  '/endpoints/$endpointId': typeof AuthenticatedEndpointsEndpointIdRoute
  '/programs/$programId': typeof AuthenticatedProgramsProgramIdRoute
  '/review/$assetId': typeof AuthenticatedReviewAssetIdRoute
  '/scanner-findings/$findingId': typeof AuthenticatedScannerFindingsFindingIdRoute
  '/urls/$urlId': typeof AuthenticatedUrlsUrlIdRoute
  '/assets/': typeof AuthenticatedAssetsIndexRoute
  '/urls/': typeof AuthenticatedUrlsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/api-endpoints': typeof AuthenticatedApiEndpointsRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/changes': typeof AuthenticatedChangesRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/js-files': typeof AuthenticatedJsFilesRoute
  '/live-hosts': typeof AuthenticatedLiveHostsRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/programs': typeof AuthenticatedProgramsRouteWithChildren
  '/review': typeof AuthenticatedReviewRouteWithChildren
  '/rules': typeof AuthenticatedRulesRoute
  '/scope': typeof AuthenticatedScopeRoute
  '/scoring': typeof AuthenticatedScoringRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/': typeof AuthenticatedIndexRoute
  '/assets/$assetId': typeof AuthenticatedAssetsAssetIdRoute
  '/endpoints/$endpointId': typeof AuthenticatedEndpointsEndpointIdRoute
  '/programs/$programId': typeof AuthenticatedProgramsProgramIdRoute
  '/review/$assetId': typeof AuthenticatedReviewAssetIdRoute
  '/scanner-findings/$findingId': typeof AuthenticatedScannerFindingsFindingIdRoute
  '/urls/$urlId': typeof AuthenticatedUrlsUrlIdRoute
  '/assets': typeof AuthenticatedAssetsIndexRoute
  '/urls': typeof AuthenticatedUrlsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/api-endpoints': typeof AuthenticatedApiEndpointsRoute
  '/_authenticated/assets': typeof AuthenticatedAssetsRouteWithChildren
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/_authenticated/changes': typeof AuthenticatedChangesRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/js-files': typeof AuthenticatedJsFilesRoute
  '/_authenticated/live-hosts': typeof AuthenticatedLiveHostsRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/programs': typeof AuthenticatedProgramsRouteWithChildren
  '/_authenticated/review': typeof AuthenticatedReviewRouteWithChildren
  '/_authenticated/rules': typeof AuthenticatedRulesRoute
  '/_authenticated/scope': typeof AuthenticatedScopeRoute
  '/_authenticated/scoring': typeof AuthenticatedScoringRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRoute
  '/_authenticated/urls': typeof AuthenticatedUrlsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/assets/$assetId': typeof AuthenticatedAssetsAssetIdRoute
  '/_authenticated/endpoints/$endpointId': typeof AuthenticatedEndpointsEndpointIdRoute
  '/_authenticated/programs/$programId': typeof AuthenticatedProgramsProgramIdRoute
  '/_authenticated/review/$assetId': typeof AuthenticatedReviewAssetIdRoute
  '/_authenticated/scanner-findings/$findingId': typeof AuthenticatedScannerFindingsFindingIdRoute
  '/_authenticated/urls/$urlId': typeof AuthenticatedUrlsUrlIdRoute
  '/_authenticated/assets/': typeof AuthenticatedAssetsIndexRoute
  '/_authenticated/urls/': typeof AuthenticatedUrlsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api-endpoints'
    | '/assets'
    | '/audit-logs'
    | '/changes'
    | '/jobs'
    | '/js-files'
    | '/live-hosts'
    | '/notes'
    | '/notifications'
    | '/programs'
    | '/review'
    | '/rules'
    | '/scope'
    | '/scoring'
    | '/settings'
    | '/tools'
    | '/urls'
    | '/assets/$assetId'
    | '/endpoints/$endpointId'
    | '/programs/$programId'
    | '/review/$assetId'
    | '/scanner-findings/$findingId'
    | '/urls/$urlId'
    | '/assets/'
    | '/urls/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/api-endpoints'
    | '/audit-logs'
    | '/changes'
    | '/jobs'
    | '/js-files'
    | '/live-hosts'
    | '/notes'
    | '/notifications'
    | '/programs'
    | '/review'
    | '/rules'
    | '/scope'
    | '/scoring'
    | '/settings'
    | '/tools'
    | '/'
    | '/assets/$assetId'
    | '/endpoints/$endpointId'
    | '/programs/$programId'
    | '/review/$assetId'
    | '/scanner-findings/$findingId'
    | '/urls/$urlId'
    | '/assets'
    | '/urls'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/api-endpoints'
    | '/_authenticated/assets'
    | '/_authenticated/audit-logs'
    | '/_authenticated/changes'
    | '/_authenticated/jobs'
    | '/_authenticated/js-files'
    | '/_authenticated/live-hosts'
    | '/_authenticated/notes'
    | '/_authenticated/notifications'
    | '/_authenticated/programs'
    | '/_authenticated/review'
    | '/_authenticated/rules'
    | '/_authenticated/scope'
    | '/_authenticated/scoring'
    | '/_authenticated/settings'
    | '/_authenticated/tools'
    | '/_authenticated/urls'
    | '/_authenticated/'
    | '/_authenticated/assets/$assetId'
    | '/_authenticated/endpoints/$endpointId'
    | '/_authenticated/programs/$programId'
    | '/_authenticated/review/$assetId'
    | '/_authenticated/scanner-findings/$findingId'
    | '/_authenticated/urls/$urlId'
    | '/_authenticated/assets/'
    | '/_authenticated/urls/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/api-endpoints': {
      id: '/_authenticated/api-endpoints'
      path: '/api-endpoints'
      fullPath: '/api-endpoints'
      preLoaderRoute: typeof AuthenticatedApiEndpointsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/changes': {
      id: '/_authenticated/changes'
      path: '/changes'
      fullPath: '/changes'
      preLoaderRoute: typeof AuthenticatedChangesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/js-files': {
      id: '/_authenticated/js-files'
      path: '/js-files'
      fullPath: '/js-files'
      preLoaderRoute: typeof AuthenticatedJsFilesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/live-hosts': {
      id: '/_authenticated/live-hosts'
      path: '/live-hosts'
      fullPath: '/live-hosts'
      preLoaderRoute: typeof AuthenticatedLiveHostsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/programs': {
      id: '/_authenticated/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof AuthenticatedProgramsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rules': {
      id: '/_authenticated/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AuthenticatedRulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scope': {
      id: '/_authenticated/scope'
      path: '/scope'
      fullPath: '/scope'
      preLoaderRoute: typeof AuthenticatedScopeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scoring': {
      id: '/_authenticated/scoring'
      path: '/scoring'
      fullPath: '/scoring'
      preLoaderRoute: typeof AuthenticatedScoringRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/urls': {
      id: '/_authenticated/urls'
      path: '/urls'
      fullPath: '/urls'
      preLoaderRoute: typeof AuthenticatedUrlsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets/': {
      id: '/_authenticated/assets/'
      path: '/'
      fullPath: '/assets/'
      preLoaderRoute: typeof AuthenticatedAssetsIndexRouteImport
      parentRoute: typeof AuthenticatedAssetsRoute
    }
    '/_authenticated/assets/$assetId': {
      id: '/_authenticated/assets/$assetId'
      path: '/$assetId'
      fullPath: '/assets/$assetId'
      preLoaderRoute: typeof AuthenticatedAssetsAssetIdRouteImport
      parentRoute: typeof AuthenticatedAssetsRoute
    }
    '/_authenticated/endpoints/$endpointId': {
      id: '/_authenticated/endpoints/$endpointId'
      path: '/endpoints/$endpointId'
      fullPath: '/endpoints/$endpointId'
      preLoaderRoute: typeof AuthenticatedEndpointsEndpointIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/programs/$programId': {
      id: '/_authenticated/programs/$programId'
      path: '/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof AuthenticatedProgramsProgramIdRouteImport
      parentRoute: typeof AuthenticatedProgramsRoute
    }
    '/_authenticated/review/$assetId': {
      id: '/_authenticated/review/$assetId'
      path: '/$assetId'
      fullPath: '/review/$assetId'
      preLoaderRoute: typeof AuthenticatedReviewAssetIdRouteImport
      parentRoute: typeof AuthenticatedReviewRoute
    }
    '/_authenticated/scanner-findings/$findingId': {
      id: '/_authenticated/scanner-findings/$findingId'
      path: '/scanner-findings/$findingId'
      fullPath: '/scanner-findings/$findingId'
      preLoaderRoute: typeof AuthenticatedScannerFindingsFindingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/urls/': {
      id: '/_authenticated/urls/'
      path: '/'
      fullPath: '/urls/'
      preLoaderRoute: typeof AuthenticatedUrlsIndexRouteImport
      parentRoute: typeof AuthenticatedUrlsRoute
    }
    '/_authenticated/urls/$urlId': {
      id: '/_authenticated/urls/$urlId'
      path: '/$urlId'
      fullPath: '/urls/$urlId'
      preLoaderRoute: typeof AuthenticatedUrlsUrlIdRouteImport
      parentRoute: typeof AuthenticatedUrlsRoute
    }
  }
}

interface AuthenticatedAssetsRouteChildren {
  AuthenticatedAssetsAssetIdRoute: typeof AuthenticatedAssetsAssetIdRoute
  AuthenticatedAssetsIndexRoute: typeof AuthenticatedAssetsIndexRoute
}

const AuthenticatedAssetsRouteChildren: AuthenticatedAssetsRouteChildren = {
  AuthenticatedAssetsAssetIdRoute: AuthenticatedAssetsAssetIdRoute,
  AuthenticatedAssetsIndexRoute: AuthenticatedAssetsIndexRoute,
}

const AuthenticatedAssetsRouteWithChildren =
  AuthenticatedAssetsRoute._addFileChildren(AuthenticatedAssetsRouteChildren)

interface AuthenticatedProgramsRouteChildren {
  AuthenticatedProgramsProgramIdRoute: typeof AuthenticatedProgramsProgramIdRoute
}

const AuthenticatedProgramsRouteChildren: AuthenticatedProgramsRouteChildren = {
  AuthenticatedProgramsProgramIdRoute: AuthenticatedProgramsProgramIdRoute,
}

const AuthenticatedProgramsRouteWithChildren =
  AuthenticatedProgramsRoute._addFileChildren(
    AuthenticatedProgramsRouteChildren,
  )

interface AuthenticatedReviewRouteChildren {
  AuthenticatedReviewAssetIdRoute: typeof AuthenticatedReviewAssetIdRoute
}

const AuthenticatedReviewRouteChildren: AuthenticatedReviewRouteChildren = {
  AuthenticatedReviewAssetIdRoute: AuthenticatedReviewAssetIdRoute,
}

const AuthenticatedReviewRouteWithChildren =
  AuthenticatedReviewRoute._addFileChildren(AuthenticatedReviewRouteChildren)

interface AuthenticatedUrlsRouteChildren {
  AuthenticatedUrlsUrlIdRoute: typeof AuthenticatedUrlsUrlIdRoute
  AuthenticatedUrlsIndexRoute: typeof AuthenticatedUrlsIndexRoute
}

const AuthenticatedUrlsRouteChildren: AuthenticatedUrlsRouteChildren = {
  AuthenticatedUrlsUrlIdRoute: AuthenticatedUrlsUrlIdRoute,
  AuthenticatedUrlsIndexRoute: AuthenticatedUrlsIndexRoute,
}

const AuthenticatedUrlsRouteWithChildren =
  AuthenticatedUrlsRoute._addFileChildren(AuthenticatedUrlsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedApiEndpointsRoute: typeof AuthenticatedApiEndpointsRoute
  AuthenticatedAssetsRoute: typeof AuthenticatedAssetsRouteWithChildren
  AuthenticatedAuditLogsRoute: typeof AuthenticatedAuditLogsRoute
  AuthenticatedChangesRoute: typeof AuthenticatedChangesRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedJsFilesRoute: typeof AuthenticatedJsFilesRoute
  AuthenticatedLiveHostsRoute: typeof AuthenticatedLiveHostsRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProgramsRoute: typeof AuthenticatedProgramsRouteWithChildren
  AuthenticatedReviewRoute: typeof AuthenticatedReviewRouteWithChildren
  AuthenticatedRulesRoute: typeof AuthenticatedRulesRoute
  AuthenticatedScopeRoute: typeof AuthenticatedScopeRoute
  AuthenticatedScoringRoute: typeof AuthenticatedScoringRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRoute
  AuthenticatedUrlsRoute: typeof AuthenticatedUrlsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedEndpointsEndpointIdRoute: typeof AuthenticatedEndpointsEndpointIdRoute
  AuthenticatedScannerFindingsFindingIdRoute: typeof AuthenticatedScannerFindingsFindingIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApiEndpointsRoute: AuthenticatedApiEndpointsRoute,
  AuthenticatedAssetsRoute: AuthenticatedAssetsRouteWithChildren,
  AuthenticatedAuditLogsRoute: AuthenticatedAuditLogsRoute,
  AuthenticatedChangesRoute: AuthenticatedChangesRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedJsFilesRoute: AuthenticatedJsFilesRoute,
  AuthenticatedLiveHostsRoute: AuthenticatedLiveHostsRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProgramsRoute: AuthenticatedProgramsRouteWithChildren,
  AuthenticatedReviewRoute: AuthenticatedReviewRouteWithChildren,
  AuthenticatedRulesRoute: AuthenticatedRulesRoute,
  AuthenticatedScopeRoute: AuthenticatedScopeRoute,
  AuthenticatedScoringRoute: AuthenticatedScoringRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedToolsRoute: AuthenticatedToolsRoute,
  AuthenticatedUrlsRoute: AuthenticatedUrlsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedEndpointsEndpointIdRoute: AuthenticatedEndpointsEndpointIdRoute,
  AuthenticatedScannerFindingsFindingIdRoute:
    AuthenticatedScannerFindingsFindingIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
