import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "@tanstack/react-router";
import { toast } from "sonner";
import type { ApiEndpointDto, AssetDto, ScannerFindingDto, ScannerFindingStatus, ScoreExplanationDto, UrlDto } from "@bountyops/shared";
import { coreApi } from "@/lib/api-client";
import { coreQ } from "@/lib/queries";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { PageHeader } from "./page-kit";
import { StatusBadge } from "./status-badge";
import { DataTable } from "./data-table";

const errorText = (error: unknown) => error instanceof Error ? error.message : "Unable to load detail workspace";
const values = (value: unknown) => Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : [];
const when = (value: string | Date | null | undefined) => value ? new Date(value).toLocaleString() : "-";
const Tags = ({ items }: { items: unknown }) => <div className="flex flex-wrap gap-1">{values(items).map((item) => <StatusBadge key={item} value={item} />)}</div>;

function ScoreSheet({ explanation, open, onClose, onOverride, pending }: { explanation?: ScoreExplanationDto; open: boolean; onClose: () => void; onOverride?: (score: number | null) => void; pending?: boolean }) {
  const [score, setScore] = useState("");
  return <Sheet open={open} onOpenChange={(next) => !next && onClose()}><SheetContent className="w-full overflow-y-auto sm:max-w-2xl"><SheetHeader><SheetTitle>Why this score?</SheetTitle><SheetDescription>Persisted rules and evidence used for prioritization.</SheetDescription></SheetHeader>{explanation && <div className="mt-6 space-y-4"><div className="grid grid-cols-4 gap-2">{[["Auto", explanation.autoScore], ["Manual", explanation.manualScore ?? "-"], ["Final", explanation.finalScore], ["Priority", explanation.priority]].map(([label, value]) => <Card key={label}><CardContent className="p-3 text-center"><p className="text-xs text-muted-foreground">{label}</p><b className="text-xl">{value}</b></CardContent></Card>)}</div><p className="text-sm">Confidence: {explanation.confidence}%</p><Tags items={explanation.categories} /><Tags items={explanation.reasonTags} />{explanation.events.map((event, index) => <div key={`${event.ruleId}-${index}`} className="rounded-md border p-3 text-sm"><div className="flex justify-between"><span>{event.ruleName ?? event.reasonTag}</span><b>{event.scoreDelta >= 0 ? "+" : ""}{event.scoreDelta}</b></div>{event.evidence && <pre className="mt-2 overflow-auto text-xs text-muted-foreground">{JSON.stringify(event.evidence, null, 2)}</pre>}</div>)}{onOverride && <div className="flex gap-2"><Input type="number" min={0} max={100} value={score} onChange={(event) => setScore(event.target.value)} placeholder="Manual score 0-100" /><Button disabled={pending || score === ""} onClick={() => onOverride(Number(score))}>Set</Button><Button variant="outline" disabled={pending || explanation.manualScore === null} onClick={() => onOverride(null)}>Clear</Button></div>}</div>}</SheetContent></Sheet>;
}

function Summary({ score, priority, status, categories, reasons }: { score: number; priority: string; status: string; categories: unknown; reasons: unknown }) {
  return <div className="grid gap-3 md:grid-cols-3"><Card><CardHeader><CardTitle>Priority</CardTitle></CardHeader><CardContent className="flex items-center gap-3"><span className="text-4xl font-bold text-primary">{score}</span><StatusBadge value={priority} /><StatusBadge value={status} /></CardContent></Card><Card><CardHeader><CardTitle>Categories</CardTitle></CardHeader><CardContent><Tags items={categories} /></CardContent></Card><Card><CardHeader><CardTitle>Reason tags</CardTitle></CardHeader><CardContent><Tags items={reasons} /></CardContent></Card></div>;
}

export function CoreAssetDetailPage({ assetId }: { assetId: string }) {
  const client = useQueryClient(); const [scoreOpen, setScoreOpen] = useState(false);
  const detail = useQuery(coreQ.assetDetail(assetId)); const urls = useQuery(coreQ.assetUrls(assetId)); const endpoints = useQuery(coreQ.assetEndpoints(assetId)); const findings = useQuery(coreQ.assetFindings(assetId));
  const override = useMutation({ mutationFn: (score: number | null) => coreApi.updateAssetManualScore(assetId, score), onSuccess: async () => { await client.invalidateQueries({ queryKey: ["core"] }); toast.success("Manual score updated"); }, onError: (error) => toast.error(errorText(error)) });
  if (detail.isLoading) return <p>Loading target workspace...</p>; if (detail.isError || !detail.data) return <p className="text-destructive">{errorText(detail.error)}</p>;
  const { asset } = detail.data; const explanation = detail.data.scoreExplanation;
  return <div className="space-y-5"><PageHeader title={asset.value} description="Target / Asset Detail Workspace" actions={<div className="flex gap-2"><Button variant="outline" asChild><Link to="/assets">Back to assets</Link></Button><Button onClick={() => setScoreOpen(true)}>Why this score?</Button></div>} /><Summary score={asset.finalScore} priority={asset.priority} status={asset.status} categories={asset.categories} reasons={asset.reasonTags} /><div className="grid gap-3 md:grid-cols-3"><Card><CardContent className="p-4"><b>DNS records</b><p className="text-2xl">{detail.data.dnsRecords.length}</p></CardContent></Card><Card><CardContent className="p-4"><b>HTTP services</b><p className="text-2xl">{detail.data.httpServices.length}</p></CardContent></Card><Card><CardContent className="p-4"><b>URLs / Endpoints / Findings</b><p className="text-2xl">{detail.data.urlsCount} / {detail.data.endpointsCount} / {detail.data.scannerFindingsCount}</p></CardContent></Card></div>
    <Card><CardHeader><CardTitle>DNS records</CardTitle></CardHeader><CardContent>{detail.data.dnsRecords.length ? detail.data.dnsRecords.map((item) => <div key={item.id} className="border-t py-2 font-mono text-xs">{item.recordType} {item.host} → {item.value}</div>) : <p className="text-sm text-muted-foreground">No DNS records.</p>}</CardContent></Card>
    <Card><CardHeader><CardTitle>HTTP services</CardTitle></CardHeader><CardContent>{detail.data.httpServices.length ? detail.data.httpServices.map((item) => <div key={item.id} className="border-t py-2 text-sm"><span className="font-mono">{item.url}</span> · {item.statusCode ?? "-"} · {item.title ?? "Untitled"}</div>) : <p className="text-sm text-muted-foreground">No HTTP services.</p>}</CardContent></Card>
    <Card><CardHeader><CardTitle>Related URLs</CardTitle></CardHeader><CardContent>{urls.data && <DataTable rows={urls.data} columns={[{ key: "url", label: "URL", render: (item: UrlDto) => <span className="font-mono text-xs">{item.url}</span> }, { key: "status", label: "HTTP", render: (item: UrlDto) => item.statusCode ?? "-" }, { key: "score", label: "Score", render: (item: UrlDto) => item.finalScore }, { key: "action", label: "", render: (item: UrlDto) => <Button asChild variant="ghost" size="sm"><Link to="/urls/$urlId" params={{ urlId: item.id }}>Detail</Link></Button> }]} />}</CardContent></Card>
    <Card><CardHeader><CardTitle>Related endpoints</CardTitle></CardHeader><CardContent>{endpoints.data && <DataTable rows={endpoints.data} columns={[{ key: "method", label: "Method", render: (item: ApiEndpointDto) => <StatusBadge value={item.method} /> }, { key: "path", label: "Path", render: (item: ApiEndpointDto) => <span className="font-mono text-xs">{item.path}</span> }, { key: "params", label: "Params", render: (item: ApiEndpointDto) => item.parametersCount ?? 0 }, { key: "action", label: "", render: (item: ApiEndpointDto) => <Button asChild variant="ghost" size="sm"><Link to="/endpoints/$endpointId" params={{ endpointId: item.id }}>Detail</Link></Button> }]} />}</CardContent></Card>
    <Card><CardHeader><CardTitle>Scanner findings</CardTitle></CardHeader><CardContent>{findings.data && <DataTable rows={findings.data} columns={[{ key: "severity", label: "Severity", render: (item: ScannerFindingDto) => <StatusBadge value={item.severity} /> }, { key: "name", label: "Scanner Finding", render: (item: ScannerFindingDto) => item.name }, { key: "status", label: "Status", render: (item: ScannerFindingDto) => <StatusBadge value={item.status} /> }, { key: "action", label: "", render: (item: ScannerFindingDto) => <Button asChild variant="ghost" size="sm"><Link to="/scanner-findings/$findingId" params={{ findingId: item.id }}>Detail</Link></Button> }]} />}</CardContent></Card>
    <Card><CardHeader><CardTitle>Changes</CardTitle></CardHeader><CardContent>{detail.data.changes.map((item) => <div key={item.id} className="border-t py-2 text-sm"><b>{item.type}</b> · {item.summary} · {when(item.createdAt)}</div>)}</CardContent></Card><ScoreSheet explanation={explanation} open={scoreOpen} onClose={() => setScoreOpen(false)} onOverride={(score) => override.mutate(score)} pending={override.isPending} /></div>;
}

export function CoreUrlDetailPage({ urlId }: { urlId: string }) {
  const client = useQueryClient(); const [scoreOpen, setScoreOpen] = useState(false); const query = useQuery(coreQ.urlDetail(urlId));
  const refresh = () => client.invalidateQueries({ queryKey: ["core"] });
  const status = useMutation({ mutationFn: (value: AssetDto["status"]) => coreApi.updateWorkspaceStatus("url", urlId, value, "Updated from URL detail"), onSuccess: async () => { await refresh(); toast.success("URL status updated"); }, onError: (error) => toast.error(errorText(error)) });
  const override = useMutation({ mutationFn: (value: number | null) => coreApi.updateUrlManualScore(urlId, value), onSuccess: async () => { await refresh(); toast.success("URL score updated"); }, onError: (error) => toast.error(errorText(error)) });
  if (query.isLoading) return <p>Loading URL workspace...</p>; if (query.isError || !query.data) return <p className="text-destructive">{errorText(query.error)}</p>; const data = query.data; const item = data.url;
  return <div className="space-y-5"><PageHeader title={item.url} description="URL Detail Workspace" actions={<div className="flex gap-2"><Button variant="outline" asChild><Link to="/assets/$assetId" params={{ assetId: item.assetId ?? "" }}>Back to target</Link></Button><Button onClick={() => setScoreOpen(true)}>Why this score?</Button></div>} /><Summary score={item.finalScore} priority={item.priority} status={item.status} categories={item.categories} reasons={item.reasonTags} /><Card><CardHeader><CardTitle>URL metadata</CardTitle></CardHeader><CardContent className="grid gap-2 text-sm md:grid-cols-2"><p><b>Host:</b> {item.host}</p><p><b>Path:</b> {item.path}</p><p><b>HTTP:</b> {item.statusCode ?? "-"}</p><p><b>Content type:</b> {item.contentType ?? "-"}</p><p><b>Query keys:</b> {values(item.queryParamKeys).join(", ") || "-"}</p><p><b>HTTP service:</b> {data.httpService?.url ?? "-"}</p></CardContent></Card><div className="flex flex-wrap gap-2">{(["promising", "manual_started", "manual_done", "potential_bug", "ignored"] as AssetDto["status"][]).map((value) => <Button key={value} variant="outline" disabled={status.isPending} onClick={() => status.mutate(value)}>{value.replaceAll("_", " ")}</Button>)}</div><Card><CardHeader><CardTitle>Endpoints</CardTitle></CardHeader><CardContent><DataTable rows={data.endpoints} columns={[{ key: "method", label: "Method", render: (entry: ApiEndpointDto) => <StatusBadge value={entry.method} /> }, { key: "path", label: "Path", render: (entry: ApiEndpointDto) => entry.path }, { key: "action", label: "", render: (entry: ApiEndpointDto) => <Button asChild variant="ghost" size="sm"><Link to="/endpoints/$endpointId" params={{ endpointId: entry.id }}>Detail</Link></Button> }]} /></CardContent></Card><Card><CardHeader><CardTitle>Scanner findings</CardTitle></CardHeader><CardContent><DataTable rows={data.scannerFindings} columns={[{ key: "severity", label: "Severity", render: (entry: ScannerFindingDto) => <StatusBadge value={entry.severity} /> }, { key: "name", label: "Scanner Finding", render: (entry: ScannerFindingDto) => entry.name }, { key: "action", label: "", render: (entry: ScannerFindingDto) => <Button asChild variant="ghost" size="sm"><Link to="/scanner-findings/$findingId" params={{ findingId: entry.id }}>Detail</Link></Button> }]} /></CardContent></Card><Card><CardHeader><CardTitle>Changes</CardTitle></CardHeader><CardContent>{data.changes.map((entry) => <p key={entry.id} className="border-t py-2 text-sm">{entry.summary} · {when(entry.createdAt)}</p>)}</CardContent></Card><ScoreSheet explanation={data.scoreExplanation} open={scoreOpen} onClose={() => setScoreOpen(false)} onOverride={(value) => override.mutate(value)} pending={override.isPending} /></div>;
}

export function CoreEndpointDetailPage({ endpointId }: { endpointId: string }) {
  const client = useQueryClient(); const [scoreOpen, setScoreOpen] = useState(false); const query = useQuery(coreQ.endpointDetail(endpointId)); const refresh = () => client.invalidateQueries({ queryKey: ["core"] });
  const status = useMutation({ mutationFn: (value: AssetDto["status"]) => coreApi.updateWorkspaceStatus("endpoint", endpointId, value, "Updated from endpoint detail"), onSuccess: async () => { await refresh(); toast.success("Endpoint status updated"); }, onError: (error) => toast.error(errorText(error)) });
  const override = useMutation({ mutationFn: (value: number | null) => coreApi.updateEndpointManualScore(endpointId, value), onSuccess: async () => { await refresh(); toast.success("Endpoint score updated"); }, onError: (error) => toast.error(errorText(error)) });
  if (query.isLoading) return <p>Loading endpoint workspace...</p>; if (query.isError || !query.data) return <p className="text-destructive">{errorText(query.error)}</p>; const data = query.data; const item = data.endpoint;
  return <div className="space-y-5"><PageHeader title={`${item.method} ${item.path}`} description="Endpoint Detail Workspace" actions={<Button onClick={() => setScoreOpen(true)}>Why this score?</Button>} /><Summary score={item.finalScore} priority={item.priority} status={item.status} categories={item.categories} reasons={item.reasonTags} /><Card><CardHeader><CardTitle>Endpoint metadata</CardTitle></CardHeader><CardContent className="grid gap-2 text-sm md:grid-cols-2"><p><b>Full URL:</b> <span className="font-mono">{item.fullUrl}</span></p><p><b>HTTP:</b> {item.statusCode ?? "-"}</p><p><b>Content type:</b> {item.contentType ?? "-"}</p><p><b>Auth required:</b> {item.authRequired}</p><p><b>Related asset:</b> {data.asset?.value ?? "-"}</p><p><b>Related URL:</b> {data.url?.url ?? "-"}</p></CardContent></Card><div className="flex flex-wrap gap-2">{(["promising", "manual_started", "manual_done", "potential_bug", "ignored"] as AssetDto["status"][]).map((value) => <Button key={value} variant="outline" disabled={status.isPending} onClick={() => status.mutate(value)}>{value.replaceAll("_", " ")}</Button>)}</div><Card><CardHeader><CardTitle>Parameters</CardTitle></CardHeader><CardContent>{data.parameters.map((parameter) => <div key={parameter.id} className="grid grid-cols-4 border-t py-2 text-sm"><span className="font-mono">{parameter.name}</span><StatusBadge value={parameter.location} /><span>{parameter.exampleValue ?? "-"}</span><span>{parameter.interesting ? "Interesting" : "-"}</span></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Scanner findings</CardTitle></CardHeader><CardContent><DataTable rows={data.scannerFindings} columns={[{ key: "severity", label: "Severity", render: (entry: ScannerFindingDto) => <StatusBadge value={entry.severity} /> }, { key: "name", label: "Scanner Finding", render: (entry: ScannerFindingDto) => entry.name }, { key: "action", label: "", render: (entry: ScannerFindingDto) => <Button asChild variant="ghost" size="sm"><Link to="/scanner-findings/$findingId" params={{ findingId: entry.id }}>Detail</Link></Button> }]} /></CardContent></Card><Card><CardHeader><CardTitle>Changes</CardTitle></CardHeader><CardContent>{data.changes.map((entry) => <p key={entry.id} className="border-t py-2 text-sm">{entry.summary} · {when(entry.createdAt)}</p>)}</CardContent></Card><ScoreSheet explanation={data.scoreExplanation} open={scoreOpen} onClose={() => setScoreOpen(false)} onOverride={(value) => override.mutate(value)} pending={override.isPending} /></div>;
}

export function CoreFindingDetailPage({ findingId }: { findingId: string }) {
  const client = useQueryClient(); const query = useQuery(coreQ.scannerFindingDetail(findingId)); const status = useMutation({ mutationFn: (value: ScannerFindingStatus) => coreApi.updateWorkspaceStatus("scanner_finding", findingId, value, "Updated from scanner finding detail"), onSuccess: async () => { await client.invalidateQueries({ queryKey: ["core"] }); toast.success("Scanner finding status updated"); }, onError: (error) => toast.error(errorText(error)) });
  if (query.isLoading) return <p>Loading scanner finding...</p>; if (query.isError || !query.data) return <p className="text-destructive">{errorText(query.error)}</p>; const data = query.data; const item = data.finding;
  return <div className="space-y-5"><PageHeader title={item.name} description="Scanner Finding Detail Workspace" /><div className="flex flex-wrap gap-2"><StatusBadge value={item.severity} /><StatusBadge value={item.tool} /><StatusBadge value={item.status} /></div><Card><CardHeader><CardTitle>Scanner Finding</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p><b>Template ID:</b> {item.templateId ?? "-"}</p><p><b>Description:</b> {item.description ?? "-"}</p><p><b>Matcher:</b> {item.matcher ?? "-"}</p><p><b>Matched URL:</b> {item.matchedUrl ?? "-"}</p><div><b>Evidence snippet:</b><pre className="mt-2 overflow-auto rounded bg-muted p-3 text-xs">{item.evidenceSnippet ?? "No evidence snippet"}</pre></div><div><b>Extracted results:</b><pre className="mt-2 overflow-auto rounded bg-muted p-3 text-xs">{JSON.stringify(item.extractedResults ?? [], null, 2)}</pre></div></CardContent></Card><Card><CardHeader><CardTitle>Related entities</CardTitle></CardHeader><CardContent className="space-y-2 text-sm">{data.asset && <Button variant="link" asChild><Link to="/assets/$assetId" params={{ assetId: data.asset.id }}>Asset: {data.asset.value}</Link></Button>}{data.url && <Button variant="link" asChild><Link to="/urls/$urlId" params={{ urlId: data.url.id }}>URL: {data.url.url}</Link></Button>}{data.endpoint && <Button variant="link" asChild><Link to="/endpoints/$endpointId" params={{ endpointId: data.endpoint.id }}>Endpoint: {data.endpoint.method} {data.endpoint.path}</Link></Button>}</CardContent></Card><div className="flex flex-wrap gap-2">{(["new", "reviewed", "interesting", "false_positive", "potential_bug", "ignored"] as ScannerFindingStatus[]).map((value) => <Button key={value} variant={value === "potential_bug" ? "default" : "outline"} disabled={status.isPending} onClick={() => status.mutate(value)}>{value === "potential_bug" ? "Potential Bug" : value.replaceAll("_", " ")}</Button>)}</div><Card><CardHeader><CardTitle>Changes</CardTitle></CardHeader><CardContent>{data.changes.map((entry) => <p key={entry.id} className="border-t py-2 text-sm">{entry.summary} · {when(entry.createdAt)}</p>)}</CardContent></Card></div>;
}
