import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import type { ChecklistItemDto, EvidenceType, ResearchNoteDto, WorkspaceEntityType } from "@bountyops/shared";
import { coreApi } from "@/lib/api-client";
import { coreQ } from "@/lib/queries";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { StatusBadge } from "./status-badge";

const message = (error: unknown) => error instanceof Error ? error.message : "Workspace action failed";
const when = (value: string) => new Date(value).toLocaleString();

export function WorkspaceSummaryCard({ entityType, entityId, statusOptions }: { entityType: WorkspaceEntityType; entityId: string; statusOptions: readonly string[] }) {
  const client = useQueryClient(); const summary = useQuery(coreQ.workspaceSummary(entityType, entityId));
  const status = useMutation({ mutationFn: (value: string) => coreApi.updateWorkspaceStatus(entityType, entityId, value, "Updated from detail workspace"), onSuccess: async () => { await client.invalidateQueries({ queryKey: ["core"] }); toast.success("Workspace status updated"); }, onError: (error) => toast.error(message(error)) });
  return <Card><CardHeader><CardTitle>Manual workspace</CardTitle></CardHeader><CardContent className="space-y-3">{summary.isLoading && <p className="text-sm text-muted-foreground">Loading workspace summary...</p>}{summary.isError && <p className="text-sm text-destructive">{message(summary.error)}</p>}{summary.data && <><div className="grid gap-2 sm:grid-cols-4"><Metric label="Notes" value={summary.data.notesCount} /><Metric label="Checklist" value={`${summary.data.checklist.done}/${summary.data.checklist.total}`} /><Metric label="Evidence" value={summary.data.evidenceCount} /><Metric label="Requests" value={summary.data.interestingRequestsCount} /></div><div className="flex flex-wrap items-center gap-2"><span className="text-xs text-muted-foreground">Status</span><StatusBadge value={summary.data.status ?? "not_applicable"} />{statusOptions.map((value) => <Button key={value} size="sm" variant="outline" disabled={status.isPending || value === summary.data?.status} onClick={() => status.mutate(value)}>{value === "potential_bug" ? "Potential Bug" : value.replaceAll("_", " ")}</Button>)}</div>{summary.data.latestStatusTransition && <p className="text-xs text-muted-foreground">Last transition: {summary.data.latestStatusTransition.oldStatus ?? "unset"} → {summary.data.latestStatusTransition.newStatus} · {when(summary.data.latestStatusTransition.createdAt)}</p>}</>}</CardContent></Card>;
}

function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-md border p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="text-xl font-semibold">{value}</p></div>; }

function NotesPanel({ entityType, entityId }: { entityType: WorkspaceEntityType; entityId: string }) {
  const client = useQueryClient(); const query = useQuery(coreQ.workspaceNotes(entityType, entityId)); const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [editing, setEditing] = useState<ResearchNoteDto | null>(null);
  const refresh = () => client.invalidateQueries({ queryKey: ["core", "workspace", entityType, entityId] });
  const save = useMutation({ mutationFn: () => editing ? coreApi.updateWorkspaceNote(editing.id, { title: title || null, body }) : coreApi.createWorkspaceNote(entityType, entityId, { title: title || null, body }), onSuccess: async () => { setTitle(""); setBody(""); setEditing(null); await refresh(); toast.success(editing ? "Note updated" : "Note created"); }, onError: (error) => toast.error(message(error)) });
  const remove = useMutation({ mutationFn: coreApi.deleteWorkspaceNote, onSuccess: async () => { await refresh(); toast.success("Note deleted"); }, onError: (error) => toast.error(message(error)) });
  const edit = (note: ResearchNoteDto) => { setEditing(note); setTitle(note.title ?? ""); setBody(note.body); };
  return <div className="space-y-4"><div className="space-y-2"><Input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Optional note title" /><Textarea value={body} onChange={(event) => setBody(event.target.value)} placeholder="Capture an observation or hypothesis..." className="min-h-28" maxLength={20_000} /><div className="flex gap-2"><Button disabled={!body.trim() || save.isPending} onClick={() => save.mutate()}>{editing ? "Save note" : "Add note"}</Button>{editing && <Button variant="outline" onClick={() => { setEditing(null); setTitle(""); setBody(""); }}>Cancel</Button>}</div></div>{query.isLoading && <p>Loading notes...</p>}{query.isError && <p className="text-destructive">{message(query.error)}</p>}{query.data?.map((note) => <div key={note.id} className="rounded-md border p-3"><div className="flex justify-between gap-3"><div><b>{note.title || "Untitled note"}</b><p className="mt-1 whitespace-pre-wrap text-sm">{note.body}</p><p className="mt-2 text-xs text-muted-foreground">{when(note.updatedAt)}</p></div><div className="flex gap-1"><Button size="sm" variant="ghost" onClick={() => edit(note)}>Edit</Button><Button size="sm" variant="ghost" disabled={remove.isPending} onClick={() => remove.mutate(note.id)}>Delete</Button></div></div></div>)}{query.data?.length === 0 && <p className="text-sm text-muted-foreground">No research notes yet.</p>}</div>;
}

function ChecklistPanel({ entityType, entityId }: { entityType: WorkspaceEntityType; entityId: string }) {
  const client = useQueryClient(); const query = useQuery(coreQ.workspaceChecklists(entityType, entityId)); const [custom, setCustom] = useState("");
  const refresh = () => client.invalidateQueries({ queryKey: ["core", "workspace", entityType, entityId] });
  const generate = useMutation({ mutationFn: () => coreApi.generateWorkspaceChecklist(entityType, entityId), onSuccess: async () => { await refresh(); toast.success("Suggested checklist refreshed"); }, onError: (error) => toast.error(message(error)) });
  const add = useMutation({ mutationFn: async () => { let checklist = query.data?.find((item) => item.source === "manual"); if (!checklist) checklist = await coreApi.createWorkspaceChecklist(entityType, entityId, { title: "Manual checks", source: "manual" }); return coreApi.createChecklistItem(checklist.id, { title: custom, source: "manual" }); }, onSuccess: async () => { setCustom(""); await refresh(); toast.success("Checklist item added"); }, onError: (error) => toast.error(message(error)) });
  const update = useMutation({ mutationFn: ({ item, status }: { item: ChecklistItemDto; status: ChecklistItemDto["status"] }) => coreApi.updateChecklistItem(item.id, { status }), onSuccess: refresh, onError: (error) => toast.error(message(error)) });
  const remove = useMutation({ mutationFn: coreApi.deleteChecklistItem, onSuccess: refresh, onError: (error) => toast.error(message(error)) });
  return <div className="space-y-4"><div className="flex flex-wrap gap-2"><Button disabled={generate.isPending} onClick={() => generate.mutate()}>Generate suggested checks</Button><Input className="max-w-md" value={custom} onChange={(event) => setCustom(event.target.value)} placeholder="Add a custom checklist item" /><Button variant="outline" disabled={!custom.trim() || add.isPending} onClick={() => add.mutate()}>Add custom item</Button></div>{query.isLoading && <p>Loading checklist...</p>}{query.isError && <p className="text-destructive">{message(query.error)}</p>}{query.data?.map((checklist) => <div key={checklist.id}><div className="mb-2 flex items-center gap-2"><b>{checklist.title}</b><StatusBadge value={checklist.source} /></div><div className="space-y-2">{checklist.items.map((item) => <div key={item.id} className="flex flex-wrap items-center gap-3 rounded-md border p-3"><select aria-label={`Status for ${item.title}`} className="rounded-md border bg-background px-2 py-1 text-sm" value={item.status} onChange={(event) => update.mutate({ item, status: event.target.value as ChecklistItemDto["status"] })}><option value="todo">Todo</option><option value="in_progress">In progress</option><option value="done">Done</option><option value="skipped">Skipped</option><option value="not_applicable">Not applicable</option></select><span className="min-w-0 flex-1 text-sm">{item.title}</span><StatusBadge value={item.priority} />{item.source === "manual" && <Button size="sm" variant="ghost" onClick={() => remove.mutate(item.id)}>Delete</Button>}</div>)}</div></div>)}{query.data?.length === 0 && <p className="text-sm text-muted-foreground">No checklist yet. Generate suggestions or add a custom item.</p>}</div>;
}

function RequestsPanel({ entityType, entityId }: { entityType: WorkspaceEntityType; entityId: string }) {
  const client = useQueryClient(); const query = useQuery(coreQ.workspaceRequests(entityType, entityId)); const [method, setMethod] = useState("GET"); const [url, setUrl] = useState(""); const [status, setStatus] = useState(""); const [notes, setNotes] = useState(""); const refresh = () => client.invalidateQueries({ queryKey: ["core", "workspace", entityType, entityId] });
  const create = useMutation({ mutationFn: () => coreApi.createInterestingRequest(entityType, entityId, { method, url: url || null, responseStatus: status ? Number(status) : null, notes: notes || null }), onSuccess: async () => { setUrl(""); setStatus(""); setNotes(""); await refresh(); toast.success("Interesting request recorded"); }, onError: (error) => toast.error(message(error)) });
  const remove = useMutation({ mutationFn: coreApi.deleteInterestingRequest, onSuccess: refresh, onError: (error) => toast.error(message(error)) });
  return <div className="space-y-4"><div className="grid gap-2 md:grid-cols-[100px_1fr_120px]"><Input value={method} onChange={(event) => setMethod(event.target.value.toUpperCase())} placeholder="Method" /><Input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="Request URL" /><Input type="number" value={status} onChange={(event) => setStatus(event.target.value)} placeholder="Response" /></div><Textarea value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Why is this request interesting?" /><Button disabled={create.isPending} onClick={() => create.mutate()}>Record request</Button>{query.data?.map((item) => <div key={item.id} className="flex justify-between gap-3 rounded-md border p-3 text-sm"><div><b>{item.method ?? "REQUEST"} {item.url ?? "No URL"}</b><p>{item.responseStatus ?? "-"} · {item.notes ?? "No notes"}</p></div><Button size="sm" variant="ghost" onClick={() => remove.mutate(item.id)}>Delete</Button></div>)}{query.data?.length === 0 && <p className="text-sm text-muted-foreground">No interesting requests recorded.</p>}</div>;
}

function EvidencePanel({ entityType, entityId }: { entityType: WorkspaceEntityType; entityId: string }) {
  const client = useQueryClient(); const query = useQuery(coreQ.workspaceEvidence(entityType, entityId)); const [title, setTitle] = useState(""); const [type, setType] = useState<EvidenceType>("observation"); const [content, setContent] = useState(""); const refresh = () => client.invalidateQueries({ queryKey: ["core", "workspace", entityType, entityId] });
  const create = useMutation({ mutationFn: () => coreApi.createEvidenceItem(entityType, entityId, { title, evidenceType: type, content: content || null }), onSuccess: async () => { setTitle(""); setContent(""); await refresh(); toast.success("Evidence item added"); }, onError: (error) => toast.error(message(error)) });
  const remove = useMutation({ mutationFn: coreApi.deleteEvidenceItem, onSuccess: refresh, onError: (error) => toast.error(message(error)) });
  return <div className="space-y-4"><div className="grid gap-2 md:grid-cols-[1fr_220px]"><Input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Evidence title" /><select className="rounded-md border bg-background px-3 text-sm" value={type} onChange={(event) => setType(event.target.value as EvidenceType)}><option value="observation">Observation</option><option value="text">Text</option><option value="request_response">Request / response</option><option value="screenshot_reference">Screenshot reference</option><option value="file_reference">File reference</option><option value="command_output">Command output</option></select></div><Textarea value={content} onChange={(event) => setContent(event.target.value)} placeholder="Text, path, or reference only; large binaries are not stored here." /><Button disabled={!title.trim() || create.isPending} onClick={() => create.mutate()}>Add evidence</Button>{query.data?.map((item) => <div key={item.id} className="flex justify-between gap-3 rounded-md border p-3 text-sm"><div><div className="flex items-center gap-2"><b>{item.title}</b><StatusBadge value={item.evidenceType} /></div><p className="mt-1 whitespace-pre-wrap text-muted-foreground">{item.content ?? item.filePath ?? item.url ?? "No inline content"}</p></div><Button size="sm" variant="ghost" onClick={() => remove.mutate(item.id)}>Delete</Button></div>)}{query.data?.length === 0 && <p className="text-sm text-muted-foreground">No evidence items yet.</p>}</div>;
}

export function EntityWorkspacePanels({ entityType, entityId }: { entityType: WorkspaceEntityType; entityId: string }) {
  return <Card><CardHeader><CardTitle>Notes, checklist, and evidence</CardTitle></CardHeader><CardContent><Tabs defaultValue="notes"><TabsList className="flex h-auto flex-wrap"><TabsTrigger value="notes">Notes</TabsTrigger><TabsTrigger value="checklist">Checklist</TabsTrigger><TabsTrigger value="requests">Interesting requests</TabsTrigger><TabsTrigger value="evidence">Evidence</TabsTrigger></TabsList><TabsContent value="notes"><NotesPanel entityType={entityType} entityId={entityId} /></TabsContent><TabsContent value="checklist"><ChecklistPanel entityType={entityType} entityId={entityId} /></TabsContent><TabsContent value="requests"><RequestsPanel entityType={entityType} entityId={entityId} /></TabsContent><TabsContent value="evidence"><EvidencePanel entityType={entityType} entityId={entityId} /></TabsContent></Tabs></CardContent></Card>;
}
