import type { Prisma } from "@bountyops/db";
import {
  CHECKLIST_ITEM_STATUSES, CHECKLIST_PRIORITIES, CHECKLIST_SOURCES, EVIDENCE_TYPES,
  SCANNER_FINDING_STATUSES, WORKSPACE_ENTITY_TYPES,
} from "@bountyops/shared";
import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { ApiError, parseRequest } from "../../utils/response.js";
import { createAuditLog } from "../audit/audit.service.js";
import { generateEntityChecklist } from "./checklist-generator.service.js";
import { resolveWorkspaceEntity } from "./entity-resolver.js";

const entityParams = z.object({ entityType: z.enum(WORKSPACE_ENTITY_TYPES), entityId: z.string().min(1) });
const idParams = (key: string) => z.object({ [key]: z.string().min(1) });
const tags = z.array(z.string().trim().min(1).max(100)).max(30);
const nullableText = (max: number) => z.string().trim().max(max).nullable().optional();
const noteCreate = z.object({ title: nullableText(200), body: z.string().trim().min(1).max(20_000), tags: tags.default([]), pinned: z.boolean().default(false) });
const noteUpdate = z.object({ title: nullableText(200), body: z.string().trim().min(1).max(20_000).optional(), tags: tags.optional(), pinned: z.boolean().optional() }).refine((value) => Object.values(value).some((item) => item !== undefined), "At least one field is required");
const checklistCreate = z.object({ title: z.string().trim().min(1).max(200), source: z.enum(CHECKLIST_SOURCES).default("manual") });
const itemCreate = z.object({ title: z.string().trim().min(1).max(300), description: nullableText(2_000), category: nullableText(100), priority: z.enum(CHECKLIST_PRIORITIES).default("medium"), order: z.number().int().min(0).default(0), source: z.enum(CHECKLIST_SOURCES).default("manual"), evidenceRef: nullableText(1_000) });
const itemUpdate = itemCreate.partial().extend({ status: z.enum(CHECKLIST_ITEM_STATUSES).optional() }).refine((value) => Object.values(value).some((item) => item !== undefined), "At least one field is required");
const jsonRecord = z.record(z.string(), z.unknown());
const requestFields = { method: nullableText(20), url: nullableText(2_000), requestHeaders: jsonRecord.nullable().optional(), requestBody: nullableText(50_000), responseStatus: z.number().int().min(100).max(599).nullable().optional(), responseHeaders: jsonRecord.nullable().optional(), responseBodySnippet: nullableText(50_000), notes: nullableText(20_000), tags: tags.optional(), source: z.string().trim().min(1).max(100).optional() };
const requestCreate = z.object(requestFields);
const requestUpdate = requestCreate.partial().refine((value) => Object.values(value).some((item) => item !== undefined), "At least one field is required");
const evidenceFields = { title: z.string().trim().min(1).max(200), evidenceType: z.enum(EVIDENCE_TYPES), content: nullableText(50_000), filePath: nullableText(2_000), url: nullableText(2_000), notes: nullableText(20_000), tags: tags.optional() };
const evidenceCreate = z.object(evidenceFields);
const evidenceUpdate = evidenceCreate.partial().refine((value) => Object.values(value).some((item) => item !== undefined), "At least one field is required");
const assetStatuses = ["new", "resolved", "live", "triaged", "promising", "manual_started", "manual_done", "potential_bug", "reported", "duplicate", "ignored", "monitor", "out_of_scope"] as const;
const statusUpdate = z.object({ status: z.string().trim().min(1).max(100), reason: nullableText(1_000) });

async function auditActivity(app: FastifyInstance, input: { userId: string; programId: string; entityType: string; entityId: string; action: string; activityType: string; summary: string; metadata?: Prisma.InputJsonValue }) {
  await Promise.all([
    app.prisma.entityChange.create({ data: { programId: input.programId, entityType: input.entityType, entityId: input.entityId, type: input.activityType, summary: input.summary, source: "manual" } }),
    createAuditLog(app.prisma, { userId: input.userId, programId: input.programId, action: input.action, entityType: input.entityType, entityId: input.entityId, metadata: input.metadata }),
  ]);
}

export async function workspaceRoutes(app: FastifyInstance): Promise<void> {
  app.get("/workspace/:entityType/:entityId/summary", { preHandler: app.requireAuth }, async (request) => {
    const params = parseRequest(entityParams, request.params); const entity = await resolveWorkspaceEntity(app.prisma, params.entityType, params.entityId);
    const [notesCount, checklistItems, evidenceCount, interestingRequestsCount, latestStatusTransition] = await Promise.all([
      app.prisma.researchNote.count({ where: params }),
      app.prisma.checklistItem.findMany({ where: { checklist: params }, select: { status: true } }),
      app.prisma.evidenceItem.count({ where: params }), app.prisma.interestingRequest.count({ where: params }),
      app.prisma.entityStatusTransition.findFirst({ where: params, orderBy: { createdAt: "desc" } }),
    ]);
    const count = (status: string) => checklistItems.filter((item) => item.status === status).length;
    return { entityType: params.entityType, entityId: params.entityId, programId: entity.programId, status: entity.status, notesCount, checklist: { total: checklistItems.length, done: count("done"), todo: count("todo"), inProgress: count("in_progress"), skipped: count("skipped") + count("not_applicable") }, evidenceCount, interestingRequestsCount, latestStatusTransition };
  });

  app.get("/workspace/:entityType/:entityId/notes", { preHandler: app.requireAuth }, async (request) => { const params = parseRequest(entityParams, request.params); await resolveWorkspaceEntity(app.prisma, params.entityType, params.entityId); return app.prisma.researchNote.findMany({ where: params, orderBy: [{ pinned: "desc" }, { updatedAt: "desc" }] }); });
  app.post("/workspace/:entityType/:entityId/notes", { preHandler: app.requireAuth }, async (request, reply) => {
    const params = parseRequest(entityParams, request.params); const body = parseRequest(noteCreate, request.body); const entity = await resolveWorkspaceEntity(app.prisma, params.entityType, params.entityId);
    const note = await app.prisma.researchNote.create({ data: { ...params, programId: entity.programId, title: body.title, body: body.body, tags: body.tags, pinned: body.pinned, createdByUserId: request.user.sub, updatedByUserId: request.user.sub } });
    await auditActivity(app, { userId: request.user.sub, programId: entity.programId, ...params, action: "workspace.note.created", activityType: "note_created", summary: "Research note created", metadata: { noteId: note.id, title: note.title } });
    return reply.code(201).send(note);
  });
  app.patch("/workspace/notes/:noteId", { preHandler: app.requireAuth }, async (request) => {
    const { noteId } = parseRequest(idParams("noteId"), request.params) as { noteId: string }; const body = parseRequest(noteUpdate, request.body); const note = await app.prisma.researchNote.findUnique({ where: { id: noteId } }); if (!note) throw new ApiError(404, "NOT_FOUND", "Research note not found");
    const updated = await app.prisma.researchNote.update({ where: { id: noteId }, data: { ...body, updatedByUserId: request.user.sub } });
    await auditActivity(app, { userId: request.user.sub, programId: note.programId, entityType: note.entityType, entityId: note.entityId, action: "workspace.note.updated", activityType: "note_updated", summary: "Research note updated", metadata: { noteId, title: updated.title } }); return updated;
  });
  app.delete("/workspace/notes/:noteId", { preHandler: app.requireAuth }, async (request, reply) => {
    const { noteId } = parseRequest(idParams("noteId"), request.params) as { noteId: string }; const note = await app.prisma.researchNote.findUnique({ where: { id: noteId } }); if (!note) throw new ApiError(404, "NOT_FOUND", "Research note not found"); await app.prisma.researchNote.delete({ where: { id: noteId } });
    await auditActivity(app, { userId: request.user.sub, programId: note.programId, entityType: note.entityType, entityId: note.entityId, action: "workspace.note.deleted", activityType: "note_deleted", summary: "Research note deleted", metadata: { noteId, title: note.title } }); return reply.code(204).send();
  });

  app.get("/workspace/:entityType/:entityId/checklists", { preHandler: app.requireAuth }, async (request) => { const params = parseRequest(entityParams, request.params); await resolveWorkspaceEntity(app.prisma, params.entityType, params.entityId); return app.prisma.manualChecklist.findMany({ where: params, include: { items: { orderBy: [{ order: "asc" }, { createdAt: "asc" }] } }, orderBy: { createdAt: "asc" } }); });
  app.post("/workspace/:entityType/:entityId/checklists/generate", { preHandler: app.requireAuth }, async (request) => { const params = parseRequest(entityParams, request.params); const checklist = await generateEntityChecklist(app.prisma, params.entityType, params.entityId); await auditActivity(app, { userId: request.user.sub, programId: checklist.programId, ...params, action: "workspace.checklist.generated", activityType: "checklist_generated", summary: "Suggested checklist generated", metadata: { checklistId: checklist.id, itemsCount: checklist.items.length } }); return checklist; });
  app.post("/workspace/:entityType/:entityId/checklists", { preHandler: app.requireAuth }, async (request, reply) => { const params = parseRequest(entityParams, request.params); const body = parseRequest(checklistCreate, request.body); const entity = await resolveWorkspaceEntity(app.prisma, params.entityType, params.entityId); const checklist = await app.prisma.manualChecklist.create({ data: { ...params, programId: entity.programId, ...body }, include: { items: true } }); await auditActivity(app, { userId: request.user.sub, programId: entity.programId, ...params, action: "workspace.checklist.created", activityType: "checklist_created", summary: "Manual checklist created", metadata: { checklistId: checklist.id, title: checklist.title } }); return reply.code(201).send(checklist); });
  app.get("/workspace/checklists/:checklistId/items", { preHandler: app.requireAuth }, async (request) => { const { checklistId } = parseRequest(idParams("checklistId"), request.params) as { checklistId: string }; if (!await app.prisma.manualChecklist.findUnique({ where: { id: checklistId } })) throw new ApiError(404, "NOT_FOUND", "Checklist not found"); return app.prisma.checklistItem.findMany({ where: { checklistId }, orderBy: [{ order: "asc" }, { createdAt: "asc" }] }); });
  app.post("/workspace/checklists/:checklistId/items", { preHandler: app.requireAuth }, async (request, reply) => { const { checklistId } = parseRequest(idParams("checklistId"), request.params) as { checklistId: string }; const body = parseRequest(itemCreate, request.body); const checklist = await app.prisma.manualChecklist.findUnique({ where: { id: checklistId } }); if (!checklist) throw new ApiError(404, "NOT_FOUND", "Checklist not found"); const item = await app.prisma.checklistItem.create({ data: { checklistId, ...body } }); await auditActivity(app, { userId: request.user.sub, programId: checklist.programId, entityType: checklist.entityType, entityId: checklist.entityId, action: "workspace.checklist_item.created", activityType: "checklist_item_created", summary: "Checklist item created", metadata: { checklistId, itemId: item.id, title: item.title } }); return reply.code(201).send(item); });
  app.patch("/workspace/checklist-items/:itemId", { preHandler: app.requireAuth }, async (request) => { const { itemId } = parseRequest(idParams("itemId"), request.params) as { itemId: string }; const body = parseRequest(itemUpdate, request.body); const item = await app.prisma.checklistItem.findUnique({ where: { id: itemId }, include: { checklist: true } }); if (!item) throw new ApiError(404, "NOT_FOUND", "Checklist item not found"); const completed = body.status === "done" ? { completedAt: new Date(), completedByUserId: request.user.sub } : body.status ? { completedAt: null, completedByUserId: null } : {}; const updated = await app.prisma.checklistItem.update({ where: { id: itemId }, data: { ...body, ...completed } }); await auditActivity(app, { userId: request.user.sub, programId: item.checklist.programId, entityType: item.checklist.entityType, entityId: item.checklist.entityId, action: "workspace.checklist_item.updated", activityType: "checklist_item_updated", summary: `Checklist item updated${body.status ? ` to ${body.status}` : ""}`, metadata: { checklistId: item.checklistId, itemId, status: updated.status } }); return updated; });
  app.delete("/workspace/checklist-items/:itemId", { preHandler: app.requireAuth }, async (request, reply) => { const { itemId } = parseRequest(idParams("itemId"), request.params) as { itemId: string }; const item = await app.prisma.checklistItem.findUnique({ where: { id: itemId }, include: { checklist: true } }); if (!item) throw new ApiError(404, "NOT_FOUND", "Checklist item not found"); await app.prisma.checklistItem.delete({ where: { id: itemId } }); await auditActivity(app, { userId: request.user.sub, programId: item.checklist.programId, entityType: item.checklist.entityType, entityId: item.checklist.entityId, action: "workspace.checklist_item.deleted", activityType: "checklist_item_deleted", summary: "Checklist item deleted", metadata: { checklistId: item.checklistId, itemId, title: item.title } }); return reply.code(204).send(); });

  app.get("/workspace/:entityType/:entityId/interesting-requests", { preHandler: app.requireAuth }, async (request) => { const params = parseRequest(entityParams, request.params); await resolveWorkspaceEntity(app.prisma, params.entityType, params.entityId); return app.prisma.interestingRequest.findMany({ where: params, orderBy: { createdAt: "desc" } }); });
  app.post("/workspace/:entityType/:entityId/interesting-requests", { preHandler: app.requireAuth }, async (request, reply) => { const params = parseRequest(entityParams, request.params); const body = parseRequest(requestCreate, request.body); const entity = await resolveWorkspaceEntity(app.prisma, params.entityType, params.entityId); const item = await app.prisma.interestingRequest.create({ data: { ...params, programId: entity.programId, ...body, requestHeaders: body.requestHeaders as Prisma.InputJsonValue | undefined, responseHeaders: body.responseHeaders as Prisma.InputJsonValue | undefined, createdByUserId: request.user.sub } }); await auditActivity(app, { userId: request.user.sub, programId: entity.programId, ...params, action: "workspace.interesting_request.created", activityType: "interesting_request_created", summary: "Interesting request recorded", metadata: { requestId: item.id, method: item.method, url: item.url, responseStatus: item.responseStatus } }); return reply.code(201).send(item); });
  app.patch("/workspace/interesting-requests/:requestId", { preHandler: app.requireAuth }, async (request) => { const { requestId } = parseRequest(idParams("requestId"), request.params) as { requestId: string }; const body = parseRequest(requestUpdate, request.body); const item = await app.prisma.interestingRequest.findUnique({ where: { id: requestId } }); if (!item) throw new ApiError(404, "NOT_FOUND", "Interesting request not found"); const updated = await app.prisma.interestingRequest.update({ where: { id: requestId }, data: { ...body, requestHeaders: body.requestHeaders as Prisma.InputJsonValue | undefined, responseHeaders: body.responseHeaders as Prisma.InputJsonValue | undefined } }); await auditActivity(app, { userId: request.user.sub, programId: item.programId, entityType: item.entityType, entityId: item.entityId, action: "workspace.interesting_request.updated", activityType: "interesting_request_updated", summary: "Interesting request updated", metadata: { requestId, method: updated.method, url: updated.url, responseStatus: updated.responseStatus } }); return updated; });
  app.delete("/workspace/interesting-requests/:requestId", { preHandler: app.requireAuth }, async (request, reply) => { const { requestId } = parseRequest(idParams("requestId"), request.params) as { requestId: string }; const item = await app.prisma.interestingRequest.findUnique({ where: { id: requestId } }); if (!item) throw new ApiError(404, "NOT_FOUND", "Interesting request not found"); await app.prisma.interestingRequest.delete({ where: { id: requestId } }); await auditActivity(app, { userId: request.user.sub, programId: item.programId, entityType: item.entityType, entityId: item.entityId, action: "workspace.interesting_request.deleted", activityType: "interesting_request_deleted", summary: "Interesting request deleted", metadata: { requestId, method: item.method, url: item.url } }); return reply.code(204).send(); });

  app.get("/workspace/:entityType/:entityId/evidence", { preHandler: app.requireAuth }, async (request) => { const params = parseRequest(entityParams, request.params); await resolveWorkspaceEntity(app.prisma, params.entityType, params.entityId); return app.prisma.evidenceItem.findMany({ where: params, orderBy: { createdAt: "desc" } }); });
  app.post("/workspace/:entityType/:entityId/evidence", { preHandler: app.requireAuth }, async (request, reply) => { const params = parseRequest(entityParams, request.params); const body = parseRequest(evidenceCreate, request.body); const entity = await resolveWorkspaceEntity(app.prisma, params.entityType, params.entityId); const item = await app.prisma.evidenceItem.create({ data: { ...params, programId: entity.programId, ...body, createdByUserId: request.user.sub } }); await auditActivity(app, { userId: request.user.sub, programId: entity.programId, ...params, action: "workspace.evidence.created", activityType: "evidence_created", summary: "Evidence item created", metadata: { evidenceId: item.id, title: item.title, evidenceType: item.evidenceType } }); return reply.code(201).send(item); });
  app.patch("/workspace/evidence/:evidenceId", { preHandler: app.requireAuth }, async (request) => { const { evidenceId } = parseRequest(idParams("evidenceId"), request.params) as { evidenceId: string }; const body = parseRequest(evidenceUpdate, request.body); const item = await app.prisma.evidenceItem.findUnique({ where: { id: evidenceId } }); if (!item) throw new ApiError(404, "NOT_FOUND", "Evidence item not found"); const updated = await app.prisma.evidenceItem.update({ where: { id: evidenceId }, data: body }); await auditActivity(app, { userId: request.user.sub, programId: item.programId, entityType: item.entityType, entityId: item.entityId, action: "workspace.evidence.updated", activityType: "evidence_updated", summary: "Evidence item updated", metadata: { evidenceId, title: updated.title, evidenceType: updated.evidenceType } }); return updated; });
  app.delete("/workspace/evidence/:evidenceId", { preHandler: app.requireAuth }, async (request, reply) => { const { evidenceId } = parseRequest(idParams("evidenceId"), request.params) as { evidenceId: string }; const item = await app.prisma.evidenceItem.findUnique({ where: { id: evidenceId } }); if (!item) throw new ApiError(404, "NOT_FOUND", "Evidence item not found"); await app.prisma.evidenceItem.delete({ where: { id: evidenceId } }); await auditActivity(app, { userId: request.user.sub, programId: item.programId, entityType: item.entityType, entityId: item.entityId, action: "workspace.evidence.deleted", activityType: "evidence_deleted", summary: "Evidence item deleted", metadata: { evidenceId, title: item.title, evidenceType: item.evidenceType } }); return reply.code(204).send(); });

  app.patch("/workspace/:entityType/:entityId/status", { preHandler: app.requireAuth }, async (request) => {
    const params = parseRequest(entityParams, request.params); const body = parseRequest(statusUpdate, request.body); const entity = await resolveWorkspaceEntity(app.prisma, params.entityType, params.entityId);
    if (params.entityType === "scanner_finding") { if (!SCANNER_FINDING_STATUSES.includes(body.status as never)) throw new ApiError(400, "BAD_REQUEST", "Invalid scanner finding status"); await app.prisma.scannerFinding.update({ where: { id: params.entityId }, data: { status: body.status } }); }
    else if (["asset", "url", "endpoint"].includes(params.entityType)) { if (!assetStatuses.includes(body.status as never)) throw new ApiError(400, "BAD_REQUEST", "Invalid workspace status"); if (params.entityType === "asset") await app.prisma.asset.update({ where: { id: params.entityId }, data: { status: body.status, lastChangedAt: new Date() } }); if (params.entityType === "url") await app.prisma.url.update({ where: { id: params.entityId }, data: { status: body.status, lastReviewedAt: new Date() } }); if (params.entityType === "endpoint") await app.prisma.apiEndpoint.update({ where: { id: params.entityId }, data: { status: body.status } }); }
    else throw new ApiError(400, "BAD_REQUEST", "This entity type does not support status updates");
    const transition = await app.prisma.entityStatusTransition.create({ data: { programId: entity.programId, ...params, oldStatus: entity.status, newStatus: body.status, reason: body.reason, createdByUserId: request.user.sub } });
    await auditActivity(app, { userId: request.user.sub, programId: entity.programId, ...params, action: "workspace.status.updated", activityType: "status_changed", summary: `Status changed from ${entity.status ?? "unset"} to ${body.status}`, metadata: { transitionId: transition.id, oldStatus: entity.status, newStatus: body.status, reason: body.reason } });
    return { entityType: params.entityType, entityId: params.entityId, oldStatus: entity.status, status: body.status, transition };
  });
}
