import { Prisma } from "@bountyops/db";
import { CHANGE_IMPORTANCE_VALUES, DEFAULT_PROGRAM_NOTIFICATION_EVENT_TYPES, NOTIFICATION_CHANNELS, NOTIFICATION_DELIVERY_QUEUE_NAME, NOTIFICATION_DELIVERY_STATUSES, SUPPORTED_NOTIFICATION_EVENT_TYPES } from "@bountyops/shared";
import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { ApiError, parseRequest } from "../../utils/response.js";
import { createAuditLog } from "../audit/audit.service.js";
import { enqueueNotificationDelivery, notificationDeliveryJobId } from "./notification-dispatcher.service.js";
import { evaluateNotificationEligibility } from "./notification-eligibility.service.js";

const programParams = z.object({ programId: z.string().min(1) }); const eventParams = z.object({ id: z.string().min(1) });
const preferenceBody = z.object({ enabled: z.boolean(), telegramEnabled: z.boolean(), minImportance: z.enum(CHANGE_IMPORTANCE_VALUES), eventTypes: z.array(z.enum(SUPPORTED_NOTIFICATION_EVENT_TYPES)).max(50) });
const deliveryQuery = z.object({ programId: z.string().optional(), status: z.enum(NOTIFICATION_DELIVERY_STATUSES).optional(), eventType: z.string().optional(), importance: z.enum(CHANGE_IMPORTANCE_VALUES).optional(), channel: z.enum(NOTIFICATION_CHANNELS).optional(), limit: z.coerce.number().int().min(1).max(500).default(100) });
const defaultPreference = (programId: string) => ({ id: null, programId, enabled: false, telegramEnabled: false, minImportance: "medium", eventTypes: [...DEFAULT_PROGRAM_NOTIFICATION_EVENT_TYPES], createdAt: null, updatedAt: null });
const json = (value: unknown) => JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue;

export async function notificationDeliveryRoutes(app: FastifyInstance) {
  app.get("/programs/:programId/notification-preferences", { preHandler: app.requireAuth }, async request => { const { programId } = parseRequest(programParams, request.params); if (!await app.prisma.program.findUnique({ where: { id: programId }, select: { id: true } })) throw new ApiError(404, "NOT_FOUND", "Program not found"); const preference = await app.prisma.programNotificationPreference.findUnique({ where: { programId } }); return preference ?? defaultPreference(programId); });
  app.put("/programs/:programId/notification-preferences", { preHandler: app.requireAuth }, async request => { const { programId } = parseRequest(programParams, request.params); const body = parseRequest(preferenceBody, request.body); if (!await app.prisma.program.findUnique({ where: { id: programId }, select: { id: true } })) throw new ApiError(404, "NOT_FOUND", "Program not found"); const eventTypes = [...new Set(body.eventTypes)]; const preference = await app.prisma.programNotificationPreference.upsert({ where: { programId }, update: { ...body, eventTypes: json(eventTypes) }, create: { programId, ...body, eventTypes: json(eventTypes) } }); await createAuditLog(app.prisma, { userId: request.user.sub, programId, action: "notification_preferences.updated", entityType: "program_notification_preference", entityId: preference.id, metadata: { enabled: preference.enabled, telegramEnabled: preference.telegramEnabled, minImportance: preference.minImportance, eventTypeCount: eventTypes.length } }); return preference; });
  app.get("/notification-deliveries", { preHandler: app.requireAuth }, async request => { const query = parseRequest(deliveryQuery, request.query); const deliveries = await app.prisma.notificationDelivery.findMany({ where: { channel: query.channel, status: query.status, notificationEvent: { programId: query.programId, eventType: query.eventType, importance: query.importance } }, include: { notificationEvent: true }, orderBy: { createdAt: "desc" }, take: query.limit }); const programIds = [...new Set(deliveries.map(item => item.notificationEvent.programId).filter((id): id is string => Boolean(id)))]; const programs = new Map((await app.prisma.program.findMany({ where: { id: { in: programIds } }, select: { id: true, name: true } })).map(item => [item.id, item])); return deliveries.map(item => ({ ...item, event: item.notificationEvent, program: item.notificationEvent.programId ? programs.get(item.notificationEvent.programId) ?? null : null, notificationEvent: undefined })); });
  app.get("/notification-events/:id/deliveries", { preHandler: app.requireAuth }, async request => { const { id } = parseRequest(eventParams, request.params); if (!await app.prisma.notificationEvent.findUnique({ where: { id }, select: { id: true } })) throw new ApiError(404, "NOT_FOUND", "Notification event not found"); return app.prisma.notificationDelivery.findMany({ where: { notificationEventId: id }, orderBy: { createdAt: "desc" } }); });
  app.post("/notification-events/:id/retry", { preHandler: app.requireAuth }, async request => { const { id } = parseRequest(eventParams, request.params); const event = await app.prisma.notificationEvent.findUnique({ where: { id }, include: { deliveries: true } }); if (!event) throw new ApiError(404, "NOT_FOUND", "Notification event not found"); const delivery = event.deliveries.find(item => item.channel === "telegram"); if (!delivery || delivery.status !== "failed" || event.status !== "failed") throw new ApiError(409, "CONFLICT", "Only failed notification deliveries can be retried"); await app.prisma.notificationEvent.update({ where: { id }, data: { status: "pending", deliveredAt: null } }); const eligibility = await evaluateNotificationEligibility(app.prisma, { ...event, status: "pending" }); if (!eligibility.eligible) { await app.prisma.notificationEvent.update({ where: { id }, data: { status: "failed" } }); throw new ApiError(409, "CONFLICT", `Notification is not currently eligible: ${eligibility.reason}`); } const updated = await app.prisma.notificationDelivery.update({ where: { id: delivery.id }, data: { status: "queued", queuedAt: new Date(), failedAt: null, nextRetryAt: null, lastError: null } }); const queued = await app.notificationQueue.getJob(notificationDeliveryJobId(event.id)); if (queued) await queued.remove().catch(() => undefined); await enqueueNotificationDelivery(app.notificationQueue, { notificationEventId: event.id, notificationDeliveryId: updated.id, channel: "telegram" }); await createAuditLog(app.prisma, { userId: request.user.sub, programId: event.programId ?? undefined, action: "notification.delivery.retried", entityType: "notification_delivery", entityId: delivery.id, metadata: { notificationEventId: event.id, deliveryId: delivery.id, eventType: event.eventType, importance: event.importance } }); return updated; });
  app.get("/notifications/queue/health", { preHandler: app.requireAuth }, async (_request, reply) => { try { const [waiting, active, completed, failed, delayed] = await Promise.all([app.notificationQueue.getWaitingCount(), app.notificationQueue.getActiveCount(), app.notificationQueue.getCompletedCount(), app.notificationQueue.getFailedCount(), app.notificationQueue.getDelayedCount()]); return { queueName: NOTIFICATION_DELIVERY_QUEUE_NAME, redis: "ok", counts: { waiting, active, completed, failed, delayed }, timestamp: new Date().toISOString() }; } catch { return reply.code(503).send({ queueName: NOTIFICATION_DELIVERY_QUEUE_NAME, redis: "error", counts: { waiting: 0, active: 0, completed: 0, failed: 0, delayed: 0 }, timestamp: new Date().toISOString() }); } });
}
