import dotenv from "dotenv";
import { fileURLToPath } from "node:url";
import { buildApp } from "../src/app.js";

dotenv.config({ path: fileURLToPath(new URL("../../../.env", import.meta.url)), quiet: true });
const expectStatus = (actual: number, expected: number, label: string) => { if (actual !== expected) throw new Error(`${label}: expected HTTP ${expected}, received ${actual}`); };

async function main() {
  const app = await buildApp(); let programId = "";
  try {
    const login = await app.inject({ method: "POST", url: "/auth/login", payload: { email: process.env.ADMIN_EMAIL, password: process.env.ADMIN_PASSWORD } }); expectStatus(login.statusCode, 200, "login");
    const cookie = login.headers["set-cookie"]?.split(";")[0]; if (!cookie) throw new Error("No session cookie"); const headers = { cookie };
    const programResponse = await app.inject({ method: "POST", url: "/programs", headers, payload: { platform: "custom", name: `Phase 9 smoke ${Date.now()}`, status: "active", huntingStatus: "ongoing" } }); expectStatus(programResponse.statusCode, 201, "program create"); programId = programResponse.json().id as string;
    expectStatus((await app.inject({ method: "POST", url: `/programs/${programId}/scopes`, headers, payload: { asset: "*.example.com", assetType: "wildcard_domain", isInScope: true, bountyEligible: true } })).statusCode, 201, "scope create");
    expectStatus((await app.inject({ method: "PUT", url: `/programs/${programId}/rules`, headers, payload: { automationAllowed: "yes", aggressiveAllowed: false, forbiddenActions: ["dos", "bruteforce"], authTestingAllowed: false, dosTestingAllowed: false } })).statusCode, 200, "rules update");
    const asset = await app.prisma.asset.create({ data: { programId, type: "subdomain", value: "api.example.com", normalizedValue: "api.example.com", scopeStatus: "in_scope", status: "promising", categories: ["api", "graphql"], reasonTags: ["api_host", "graphql_detected"], sourceTools: ["phase9_fixture"], autoScore: 14, finalScore: 14 } });
    const urlResponse = await app.inject({ method: "POST", url: "/urls", headers, payload: { programId, assetId: asset.id, url: "https://api.example.com/graphql", sourceTools: ["manual"], title: "GraphQL Playground", statusCode: 200, contentType: "application/json" } }); expectStatus(urlResponse.statusCode, 201, "URL create"); const url = urlResponse.json() as { id: string };
    const endpointResponse = await app.inject({ method: "POST", url: "/endpoints", headers, payload: { programId, assetId: asset.id, urlId: url.id, method: "POST", path: "/graphql", fullUrl: "https://api.example.com/graphql", statusCode: 200, contentType: "application/json", authRequired: "unknown", source: "manual", parameters: [{ name: "query", location: "body", interesting: true }] } }); expectStatus(endpointResponse.statusCode, 201, "endpoint create"); const endpoint = endpointResponse.json() as { id: string };
    const findingResponse = await app.inject({ method: "POST", url: "/scanner-findings", headers, payload: { programId, assetId: asset.id, urlId: url.id, endpointId: endpoint.id, tool: "manual", severity: "high", name: "GraphQL Introspection Candidate", matchedUrl: "https://api.example.com/graphql", evidenceSnippet: "Controlled fixture only" } }); expectStatus(findingResponse.statusCode, 201, "finding create"); const finding = findingResponse.json() as { id: string };

    const entities = [["asset", asset.id, "manual_started"], ["url", url.id, "manual_started"], ["endpoint", endpoint.id, "manual_started"], ["scanner_finding", finding.id, "potential_bug"]] as const;
    for (const [entityType, entityId, nextStatus] of entities) {
      const noteResponse = await app.inject({ method: "POST", url: `/workspace/${entityType}/${entityId}/notes`, headers, payload: { title: "Smoke observation", body: "Controlled Phase 9 note", tags: ["smoke"] } }); expectStatus(noteResponse.statusCode, 201, `${entityType} note create`); const note = noteResponse.json() as { id: string };
      const notes = await app.inject({ method: "GET", url: `/workspace/${entityType}/${entityId}/notes`, headers }); expectStatus(notes.statusCode, 200, `${entityType} notes read`); if ((notes.json() as unknown[]).length !== 1) throw new Error(`${entityType} note missing`);
      expectStatus((await app.inject({ method: "PATCH", url: `/workspace/notes/${note.id}`, headers, payload: { body: "Controlled Phase 9 note updated", pinned: true } })).statusCode, 200, `${entityType} note update`);

      const generated = await app.inject({ method: "POST", url: `/workspace/${entityType}/${entityId}/checklists/generate`, headers }); expectStatus(generated.statusCode, 200, `${entityType} checklist generate`); const generatedBody = generated.json() as { id: string; items: unknown[] }; if (!generatedBody.items.length) throw new Error(`${entityType} generated no checklist items`);
      const generatedAgain = await app.inject({ method: "POST", url: `/workspace/${entityType}/${entityId}/checklists/generate`, headers }); expectStatus(generatedAgain.statusCode, 200, `${entityType} checklist regenerate`); if ((generatedAgain.json() as { items: unknown[] }).items.length !== generatedBody.items.length) throw new Error(`${entityType} checklist generation was not idempotent`);
      const manual = await app.inject({ method: "POST", url: `/workspace/${entityType}/${entityId}/checklists`, headers, payload: { title: "Smoke manual checks", source: "manual" } }); expectStatus(manual.statusCode, 201, `${entityType} manual checklist`); const manualId = (manual.json() as { id: string }).id;
      const custom = await app.inject({ method: "POST", url: `/workspace/checklists/${manualId}/items`, headers, payload: { title: "Review controlled fixture", priority: "high", source: "manual" } }); expectStatus(custom.statusCode, 201, `${entityType} custom item`); const customId = (custom.json() as { id: string }).id;
      expectStatus((await app.inject({ method: "PATCH", url: `/workspace/checklist-items/${customId}`, headers, payload: { status: "done", evidenceRef: "phase9-smoke" } })).statusCode, 200, `${entityType} checklist done`);

      expectStatus((await app.inject({ method: "POST", url: `/workspace/${entityType}/${entityId}/interesting-requests`, headers, payload: { method: "POST", url: "https://api.example.com/graphql", requestBody: "SENSITIVE_REQUEST_SENTINEL", responseStatus: 200, responseBodySnippet: "SENSITIVE_RESPONSE_SENTINEL", notes: "Controlled request fixture", tags: ["graphql"] } })).statusCode, 201, `${entityType} interesting request`);
      expectStatus((await app.inject({ method: "POST", url: `/workspace/${entityType}/${entityId}/evidence`, headers, payload: { title: "Controlled response", evidenceType: "request_response", content: "SENSITIVE_EVIDENCE_SENTINEL", notes: "No network activity" } })).statusCode, 201, `${entityType} evidence`);
      expectStatus((await app.inject({ method: "PATCH", url: `/workspace/${entityType}/${entityId}/status`, headers, payload: { status: nextStatus, reason: "Phase 9 smoke transition" } })).statusCode, 200, `${entityType} status`);
      const summary = await app.inject({ method: "GET", url: `/workspace/${entityType}/${entityId}/summary`, headers }); expectStatus(summary.statusCode, 200, `${entityType} summary`); const value = summary.json() as { notesCount: number; evidenceCount: number; interestingRequestsCount: number; checklist: { total: number; done: number }; latestStatusTransition: unknown }; if (value.notesCount !== 1 || value.evidenceCount !== 1 || value.interestingRequestsCount !== 1 || value.checklist.done !== 1 || value.checklist.total <= 1 || !value.latestStatusTransition) throw new Error(`${entityType} workspace summary incorrect`);
    }

    const disposableNote = await app.inject({ method: "POST", url: `/workspace/asset/${asset.id}/notes`, headers, payload: { body: "Disposable note" } }); expectStatus(disposableNote.statusCode, 201, "disposable note create"); expectStatus((await app.inject({ method: "DELETE", url: `/workspace/notes/${(disposableNote.json() as { id: string }).id}`, headers })).statusCode, 204, "note delete");
    const disposableRequest = await app.inject({ method: "POST", url: `/workspace/asset/${asset.id}/interesting-requests`, headers, payload: { method: "GET", notes: "Disposable request" } }); expectStatus(disposableRequest.statusCode, 201, "disposable request create"); const disposableRequestId = (disposableRequest.json() as { id: string }).id; expectStatus((await app.inject({ method: "PATCH", url: `/workspace/interesting-requests/${disposableRequestId}`, headers, payload: { notes: "Updated disposable request" } })).statusCode, 200, "request update"); expectStatus((await app.inject({ method: "DELETE", url: `/workspace/interesting-requests/${disposableRequestId}`, headers })).statusCode, 204, "request delete");
    const disposableEvidence = await app.inject({ method: "POST", url: `/workspace/asset/${asset.id}/evidence`, headers, payload: { title: "Disposable evidence", evidenceType: "text", content: "temporary" } }); expectStatus(disposableEvidence.statusCode, 201, "disposable evidence create"); const disposableEvidenceId = (disposableEvidence.json() as { id: string }).id; expectStatus((await app.inject({ method: "PATCH", url: `/workspace/evidence/${disposableEvidenceId}`, headers, payload: { title: "Updated disposable evidence" } })).statusCode, 200, "evidence update"); expectStatus((await app.inject({ method: "DELETE", url: `/workspace/evidence/${disposableEvidenceId}`, headers })).statusCode, 204, "evidence delete");
    const transitions = await app.prisma.entityStatusTransition.count({ where: { programId } }); if (transitions !== entities.length) throw new Error("Status transitions were not persisted");
    const changes = await app.prisma.entityChange.count({ where: { programId, type: { in: ["note_created", "checklist_generated", "evidence_created", "interesting_request_created", "status_changed"] } } }); if (changes < entities.length * 5) throw new Error("Workspace entity changes are missing");
    const auditResponse = await app.inject({ method: "GET", url: `/audit-logs?programId=${programId}&limit=100`, headers }); expectStatus(auditResponse.statusCode, 200, "audit read"); const auditText = JSON.stringify(auditResponse.json()); for (const secret of ["SENSITIVE_REQUEST_SENTINEL", "SENSITIVE_RESPONSE_SENTINEL", "SENSITIVE_EVIDENCE_SENTINEL"]) if (auditText.includes(secret)) throw new Error("Sensitive workspace content leaked into audit metadata");
    for (const action of ["workspace.note.created", "workspace.checklist.generated", "workspace.interesting_request.created", "workspace.evidence.created", "workspace.status.updated"]) if (!auditText.includes(action)) throw new Error(`Missing audit action ${action}`);
    console.log(JSON.stringify({ success: true, publicRecon: "not_run", entitiesVerified: entities.map(([type]) => type), checklistIdempotent: true, sensitiveAuditContentStored: false }, null, 2));
  } finally {
    if (programId) await app.prisma.$transaction([app.prisma.entityStatusTransition.deleteMany({ where: { programId } }), app.prisma.scoreEvent.deleteMany({ where: { programId } }), app.prisma.entityClassification.deleteMany({ where: { programId } }), app.prisma.entityChange.deleteMany({ where: { programId } }), app.prisma.scopeGuardCheck.deleteMany({ where: { programId } }), app.prisma.auditLog.deleteMany({ where: { programId } }), app.prisma.program.deleteMany({ where: { id: programId } })]);
    await app.close();
  }
}

main().catch((error) => { console.error(error instanceof Error ? error.message : error); process.exitCode = 1; });
