import { queryOptions } from "@tanstack/react-query";
import { api } from "./api-client";

export const q = {
  dashboard: (programId?: string) => queryOptions({ queryKey: ["dashboard", programId], queryFn: () => api.dashboard(programId) }),
  programs: () => queryOptions({ queryKey: ["programs"], queryFn: api.programs }),
  program: (id: string) => queryOptions({ queryKey: ["program", id], queryFn: () => api.program(id) }),
  scopes: (programId?: string) => queryOptions({ queryKey: ["scopes", programId], queryFn: () => api.scopes(programId) }),
  rules: (programId: string) => queryOptions({ queryKey: ["rules", programId], queryFn: () => api.rules(programId) }),
  jobs: (programId?: string) => queryOptions({ queryKey: ["jobs", programId], queryFn: () => api.jobs(programId) }),
  assets: (programId?: string) => queryOptions({ queryKey: ["assets", programId], queryFn: () => api.assets(programId) }),
  urls: (programId?: string) => queryOptions({ queryKey: ["urls", programId], queryFn: () => api.urls(programId) }),
  services: (programId?: string) => queryOptions({ queryKey: ["services", programId], queryFn: () => api.services(programId) }),
  endpoints: (programId?: string) => queryOptions({ queryKey: ["endpoints", programId], queryFn: () => api.apiEndpoints(programId) }),
  jsFiles: (programId?: string) => queryOptions({ queryKey: ["js-files", programId], queryFn: () => api.jsFiles(programId) }),
  notes: (programId?: string) => queryOptions({ queryKey: ["notes", programId], queryFn: () => api.notes(programId) }),
  changes: (programId?: string) => queryOptions({ queryKey: ["changes", programId], queryFn: () => api.changes(programId) }),
  schedules: (programId: string) => queryOptions({ queryKey: ["schedules", programId], queryFn: () => api.schedules(programId) }),
  pipeline: (programId: string) => queryOptions({ queryKey: ["pipeline", programId], queryFn: () => api.pipeline(programId) }),
  nuclei: (assetId: string) => queryOptions({ queryKey: ["nuclei", assetId], queryFn: () => api.nucleiFindings(assetId) }),
  requests: (assetId: string) => queryOptions({ queryKey: ["requests", assetId], queryFn: () => api.interestingRequests(assetId) }),
  tools: () => queryOptions({ queryKey: ["tools"], queryFn: api.tools }),
  scoring: () => queryOptions({ queryKey: ["scoring"], queryFn: api.scoring }),
  notifications: () => queryOptions({ queryKey: ["notifications"], queryFn: api.notifications }),
  settings: () => queryOptions({ queryKey: ["settings"], queryFn: api.settings }),
  checklist: (id: string) => queryOptions({ queryKey: ["checklist", id], queryFn: () => api.checklist(id) }),
  assetDetail: (id: string) => queryOptions({ queryKey: ["asset-detail", id], queryFn: () => api.assetDetail(id) }),
  urlDetail: (id: string) => queryOptions({ queryKey: ["url-detail", id], queryFn: () => api.urlDetail(id) }),
  endpointDetail: (id: string) => queryOptions({ queryKey: ["endpoint-detail", id], queryFn: () => api.endpointDetail(id) }),
  findingDetail: (id: string) => queryOptions({ queryKey: ["finding-detail", id], queryFn: () => api.findingDetail(id) }),
  entityNotes: (entityType: string, entityId: string) => queryOptions({ queryKey: ["entity-notes", entityType, entityId], queryFn: () => api.entityNotes(entityType as never, entityId) }),
  entityChecklist: (entityType: "asset" | "url" | "endpoint", entityId: string) => queryOptions({ queryKey: ["entity-checklist", entityType, entityId], queryFn: () => api.entityChecklist(entityType, entityId) }),
  entityRequests: (entityType: string, entityId: string) => queryOptions({ queryKey: ["entity-requests", entityType, entityId], queryFn: () => api.entityRequests(entityType as never, entityId) }),
  scannerFindings: (programId?: string) => queryOptions({ queryKey: ["scanner-findings", programId], queryFn: () => api.scannerFindings(programId) }),
  discoveredEndpoints: (programId?: string) => queryOptions({ queryKey: ["discovered-endpoints", programId], queryFn: () => api.discoveredEndpoints(programId) }),
};
